services:
  - type: web
    name: originsync-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: .

  - type: web
    name: originsync-dashboard
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
